### ISSUE TITLE
Update to 1.16?

### ISSUE THREAD

**Issue by TheGam1ngWizard** [Cynadyde/Teleportals#1]
Is there going to be an update to 1.16 for this plugin?

**Comment by Cynadyde** [comment]
Something changed in 1.16 where ender pearls don't collide with the end gateway anymore.
I opened an issue, but I don't think it will be resolved: https://hub.spigotmc.org/jira/browse/SPIGOT-5978

It's been almost a year since then, so maybe I'll give the plugin another try.

**Comment by Uboaaaaa** [comment]
I wish to see it being fix and updated to 1.16. This is our favorite teleport solution amongst all other complex portal plugins.

**Comment by Cynadyde** [comment]
I updated it for 1.16. Hope you enjoy!
