### ISSUE TITLE
Player suffocates

### ISSUE THREAD

**Issue by Uboaaaaa** [Cynadyde/Teleportals#2]
I think this issue has been there for a while... Players can be placed into a non-transparent block when using the gate, which makes them suffocate.

Possibly simulate how vanilla gateway portals work, and place the player in a safe position around the portal instead?

Another idea would be that the prism saves the player's position when linking the destination portal, and they will be placed into this position when they travels through it. Probably reverse their facing so it appears like they hopped out from the portal.

**Comment by Cynadyde** [comment]
I see what you mean... I could have the exit portal attempt to deliver the player on a side that isn't obstructed, just in case you build the teleportal against a wall. But, I'll keep it so they still spawn into a wall if the teleportal is blocked on all four sides :P

**Comment by Cynadyde** [comment]
Regenerate your config with 1.16.5-1 to see all the new teleportal options!
